#!/bin/sh

ip address add 192.168.8.1/24 dev $1
ip link set $1 up
sysctl -w net.ipv4.ip_forward=1
route add -host 192.168.8.10 dev $1
iptables -t nat -A POSTROUTING -s 192.168.8.0/24 -o wlp2s0 -j MASQUERADE
